second_app_6_0_go/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get  "login", to: "users#login"
  get  "about_us", to: "pages#about_us" 
  get "test", to: "pages#test"
  root "pages#index"
end

second_app_6_0_go/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

second_app_6_0_go/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

second_app_6_0_go/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    Rails.logger.info("##########################################################################################")
    Rails.logger.info("##########################################################################################")
    Rails.logger.info("##########################################################################################")
    Rails.logger.info("############Agrega un parrafo en la vista index.html.erb con el texto: Rails es genial!!!################")
    Rails.logger.info("##########################################################################################")
    Rails.logger.info("##########################################################################################")
    Rails.logger.info("##########################################################################################")
  end

  def about_us
  end

  def test 
    @test_info = Date.today
    @banana = "Banana!"
  end
end

second_app_6_0_go/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
  end
end

second_app_6_0_go/app/helpers/application_helper.rb
module ApplicationHelper
end

second_app_6_0_go/app/helpers/pages_helper.rb
module PagesHelper
end

second_app_6_0_go/app/helpers/users_helper.rb
module UsersHelper
end

second_app_6_0_go/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondApp60</title>
    <meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
​
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  </head>
​
  <body class="no-sidebar is-preload">
		<div id="page-wrapper">
    			<!-- Header -->
				<div id="header">
​
					<!-- Inner -->
						<div class="inner">
							<header>
								<h1><a href="index.html" id="logo">Second App Challenge</a></h1>
							</header>
						</div>
​
            <!-- Nav -->
						<nav id="nav">
            	<ul>
							<li>	<%= link_to('Home', root_path) %> <li>
							<li>	<%= link_to('Test', test_path) %> <li>
							<li>	<%= link_to('User', login_path) %> <li>
							<li>	<%= link_to('About us', about_us_path) %> <li>
							</ul>
						</nav>           
​
				</div>
​
        <!-- Main -->
				<div class="wrapper style1">
​
					<div class="container">
						<article id="main" class="special">
							<header>
                <%= yield %>
							</header>
            </article>   
          </div>         
        </div>
​
				<div id="footer">
					<div class="container">
						  <div class="row">
							  <div class="col-12">
​
								  <!-- Contact -->
									<section class="contact">
										<header>
											<h3>Nisl turpis nascetur interdum?</h3>
										</header>
										<p>Urna nisl non quis interdum mus ornare ridiculus egestas ridiculus lobortis vivamus tempor aliquet.</p>
										<ul class="icons">
											<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
											<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
											<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
											<li><a href="#" class="icon brands fa-pinterest"><span class="label">Pinterest</span></a></li>
											<li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
											<li><a href="#" class="icon brands fa-linkedin-in"><span class="label">Linkedin</span></a></li>
										</ul>
									</section>
​
								  <!-- Copyright -->
									<div class="copyright">
										<ul class="menu">
											<li>&copy; Challenge. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
										</ul>
									</div>
​
                </div>
							</div>
					</div>
				</div>
  
    </div>
  </body>
</html>

second_app_6_0_go/app/views/pages/about_us.html.erb
<p>Nosotros y prura vida!!!</p>

second_app_6_0_go/app/views/pages/index.html.erb
<p> Rails es genial!!!</p>

second_app_6_0_go/app/views/pages/test.html.erb
<p>hola</p>
<p><%= @test_info %></p>
<%= image_tag 'helios.jpg'%>

second_app_6_0_go/app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>